analogue_offset: -0.48
trigger_level: -440
sample_time_ns: 4
pre_trigger_samples: 500
eventcount: 100000
sleeptime: 0.003
random: True


peak_minimal_prominence_initial: 90  # in mV, minimal expected peak height for a muon. Has to be higher than noise peaks to not cause havoc!
peak_minimal_prominence_secondary: 35  # in mV, minnimal expected peak height for an electron/positron. Has to be higher than noise peaks to not cause havoc!
peak_minimal_distance: 10  # minimal distance between two peaks in number of samples (10 samples -> 40ns)
peak_minimal_width: 10  # in number of samples (10 samples -> 40ns)
trigger_position_tolerance: 20
signatures:                 # list start/stop of signatures   
  #    chA  chB  chC  chD
  - - ["+", "+", "-", "-"]  # 1st start signature (muon stopped in copper)
    - ["0", "+", "-", "-"]  # 1st stop signature (decay positron in upwards direction)
    
  - - ["+", "+", "-", "-"]  # 2nd start signature (muon stopped in copper)
    - ["-", "-", "+", "0"]  # 2nd stop signature (decay positron in downwards direction)

  - - ["+", "+", "+", "+"]  # 3rd start signature (muon stopped in lead/concrete under the detectors)
    - ["0", "0", "0", "+"]  # 3rd stop signature (decay positron in upwards direction)


chA_scaling: 1.00  # Scaling factor to match trigger thresholds for each panel
chB_scaling: 1.00  # Scaling factor to match trigger thresholds for each panel
chC_scaling: 1.00  # Scaling factor to match trigger thresholds for each panel
chD_scaling: 1.00  # Scaling factor to match trigger thresholds for each panel