# configuration of the Red Pitaya
ip: 'rp-f0c38f.local'
sample_rate: 4                          # int (see SAMPLE_RATES)
negator_IN1: false                      # bool
negator_IN2: false                      # bool
trigger_slope: 'rising'                 # str (see TRIGGER_SLOPES)
trigger_mode: 'normal'                  # str (see TRIGGER_MODES)
trigger_level: 100                      # int
number_of_samples_before_trigger: 500   # int
set_size: 100                           # int


